# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.7.0
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 15.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: Odoo modules to support management systems
repo_name: Management System
repo_slug: management-system
repo_website: https://github.com/OCA/management-system
travis_apt_packages: []
travis_apt_sources: []
