[project]
name = "odoo-addons-oca-management-system"
version = "19.0.20260613.1"
dependencies = [
    "odoo-addon-document_page_environment_manual==19.0.*",
    "odoo-addon-document_page_environmental_aspect==19.0.*",
    "odoo-addon-document_page_procedure==19.0.*",
    "odoo-addon-document_page_quality_manual==19.0.*",
    "odoo-addon-document_page_work_instruction==19.0.*",
    "odoo-addon-mgmtsystem==19.0.*",
    "odoo-addon-mgmtsystem_action==19.0.*",
    "odoo-addon-mgmtsystem_hazard==19.0.*",
    "odoo-addon-mgmtsystem_manual==19.0.*",
    "odoo-addon-mgmtsystem_survey==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
